platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9-alpine

inputs:
  - name: nist-source

outputs:
  - name: test-output

run:
  path: ./nist-source/ci/scripts/test.sh